name: Merge Check
on:
  pull_request:

jobs:
  check_commit_run:
    name: Check commit run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            const assert = (condition, message) => {
              if (!condition) {
                throw new Error(message)
              }
            }
            const res = await github.rest.checks.listSuitesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
            })
            console.log(res)
